
#!/bin/bash
# ================================================================
# cog_job.sh — SLURM job: H5 → GeoTIFF → mosaic → COG
# Runs after decomposition job succeeds (--dependency=afterok:...)
# Generated by pipeline.py — do not edit manually
# ================================================================
#SBATCH --job-name=opera_{AQUIFER}_cog
#SBATCH --account={CSC_PROJECT}
#SBATCH --partition={PARTITION}
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={CPUS}
#SBATCH --mem={MEM}
#SBATCH --time={TIME}
#SBATCH --gres=nvme:{NVME_GB}
#SBATCH --output={LOGS_DIR}/{AQUIFER}_cog_%j.out
#SBATCH --error={LOGS_DIR}/{AQUIFER}_cog_%j.err

set -euo pipefail

# ── Job parameters ────────────────────────────────────────────
AQUIFER="{AQUIFER}"
FRAMES=({FRAMES})
REPO="{REPO}"
BUCKET="{BUCKET}"

echo "============================================================"
echo "Job: $SLURM_JOB_ID — COG mosaic for aquifer $AQUIFER"
echo "Frames: ${FRAMES[*]}"
echo "Node: $(hostname)"
echo "Started: $(date -u)"
echo "============================================================"

# ── Activate Allas ────────────────────────────────────────────
module load allas
allas-conf --silent

# ── Skip if already done ──────────────────────────────────────
if a-check "$BUCKET/$AQUIFER/cog/velocity_mosaic_cog.tif" 2>/dev/null; then
    echo "COG outputs already in Allas — skipping."
    exit 0
fi

# ── Set up local NVMe scratch ─────────────────────────────────
SCRATCH="$LOCAL_SCRATCH/$SLURM_JOB_ID"
mkdir -p "$SCRATCH/$AQUIFER/cog"
echo "Scratch: $SCRATCH"

# ── Pull container ────────────────────────────────────────────
echo "Pulling container from Allas..."
a-get "$BUCKET/container/transboundary_opera.sif" -C "$SCRATCH/"
SIF="$SCRATCH/transboundary_opera.sif"

# ── Pull velocity.h5 per frame ────────────────────────────────
echo ""
echo "--- Pulling velocity.h5 per frame from Allas ---"
for FRAME in "${FRAMES[@]}"; do
    mkdir -p "$SCRATCH/$AQUIFER/$FRAME/mintpy"
    a-get "$BUCKET/$AQUIFER/$FRAME/mintpy/velocity.h5" \
        -C "$SCRATCH/$AQUIFER/$FRAME/mintpy/"
    echo "  ✓ Frame $FRAME velocity.h5"
done

# ── Pull decomposition files ──────────────────────────────────
echo ""
echo "--- Pulling decomposition outputs from Allas ---"
# Download any *Defo.h5 files at the aquifer root
a-list "$BUCKET/$AQUIFER/" 2>/dev/null | grep "Defo.h5" | while read -r obj; do
    FNAME=$(basename "$obj")
    a-get "$BUCKET/$AQUIFER/$FNAME" -C "$SCRATCH/$AQUIFER/"
    echo "  ✓ $FNAME"
done || echo "  No decomposition files found (single-pass aquifer)"

# ── Pull shapefile ────────────────────────────────────────────
echo ""
echo "--- Pulling shapefile from Allas ---"
mkdir -p "$SCRATCH/shapefiles"
for EXT in shp dbf shx prj cpg; do
    a-get "$BUCKET/shapefiles/TBA_full.$EXT" -C "$SCRATCH/shapefiles/" 2>/dev/null || true
done
echo "  ✓ TBA_full shapefile"

# ── Run COG mosaic ────────────────────────────────────────────
echo ""
echo "--- Running COG mosaic ---"
# NOTE: run_cog_mosaic.py is Phase 4 — to be implemented
# Placeholder: will be replaced with the actual COG mosaic script
apptainer exec \
    --bind "$REPO:/repo" \
    --bind "$SCRATCH:/work" \
    "$SIF" \
    python /repo/src/transboundary_opera/run_cog_mosaic.py \
        --aquifer-code "$AQUIFER" \
        --aquifer-dir  "/work/$AQUIFER" \
        --shapefile    "/work/shapefiles/TBA_full.shp" \
        --outdir       "/work/$AQUIFER/cog"

# ── Verify COG outputs ────────────────────────────────────────
echo ""
echo "--- Verifying COG outputs ---"
for f in velocity_mosaic_cog.tif timeseries_mosaic_cog.tif; do
    if [ -f "$SCRATCH/$AQUIFER/cog/$f" ]; then
        echo "  ✓ $f ($(du -sh $SCRATCH/$AQUIFER/cog/$f | cut -f1))"
    else
        echo "  ✗ $f MISSING"
        exit 1
    fi
done

# ── Upload COG outputs to Allas ───────────────────────────────
echo ""
echo "--- Uploading COG outputs to Allas ---"
a-put "$SCRATCH/$AQUIFER/cog/" \
    -b "$BUCKET" \
    --object "$AQUIFER/cog/" \
    --nc

echo "Uploaded to Allas: $BUCKET/$AQUIFER/cog/"

# ── Cleanup ───────────────────────────────────────────────────
rm -rf "$SCRATCH"

echo ""
echo "============================================================"
echo "COG mosaic for $AQUIFER complete: $(date -u)"
echo "Final outputs:"
echo "  $BUCKET/$AQUIFER/cog/velocity_mosaic_cog.tif"
echo "  $BUCKET/$AQUIFER/cog/timeseries_mosaic_cog.tif"
echo "============================================================"