#!/bin/bash
# ================================================================
# decompose_job.sh — SLURM job: ascending/descending decomposition
# Runs after ALL frame jobs succeed (--dependency=afterok:...)
# Generated by pipeline.py — do not edit manually
# ================================================================
#SBATCH --job-name=opera_{AQUIFER}_decompose
#SBATCH --account={CSC_PROJECT}
#SBATCH --partition={PARTITION}
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={CPUS}
#SBATCH --mem={MEM}
#SBATCH --time={TIME}
#SBATCH --gres=nvme:{NVME_GB}
#SBATCH --output={LOGS_DIR}/{AQUIFER}_decompose_%j.out
#SBATCH --error={LOGS_DIR}/{AQUIFER}_decompose_%j.err

set -euo pipefail

# ── Job parameters ────────────────────────────────────────────
AQUIFER="{AQUIFER}"
FRAMES=({FRAMES})
REPO="{REPO}"
BUCKET="{BUCKET}"

echo "============================================================"
echo "Job: $SLURM_JOB_ID — Decomposition for aquifer $AQUIFER"
echo "Frames: ${FRAMES[*]}"
echo "Node: $(hostname)"
echo "Started: $(date -u)"
echo "============================================================"

# ── Activate Allas ────────────────────────────────────────────
module load allas
allas-conf --silent

# ── Skip if already done ──────────────────────────────────────
# FIX: decomposer.py produces *_dhorz.h5 and *_dvert.h5, not *Defo.h5
DECOMP_COUNT=$(a-list "$BUCKET/$AQUIFER/" 2>/dev/null | grep -cE "_dhorz\.h5|_dvert\.h5" || true)
if [ "$DECOMP_COUNT" -gt 0 ]; then
    echo "Decomposition outputs already in Allas ($DECOMP_COUNT files) — skipping."
    exit 0
fi

# ── Set up local NVMe scratch ─────────────────────────────────
SCRATCH="$LOCAL_SCRATCH/$SLURM_JOB_ID"
mkdir -p "$SCRATCH"
echo "Scratch: $SCRATCH"

# ── Pull Apptainer container from Allas ──────────────────────
echo "Pulling container from Allas..."
a-get "$BUCKET/container/transboundary_opera.sif" -C "$SCRATCH/"
SIF="$SCRATCH/transboundary_opera.sif"

# ── Pull all per-frame mintpy outputs from Allas ─────────────
echo ""
echo "--- Pulling per-frame H5 files from Allas ---"
for FRAME in "${FRAMES[@]}"; do
    mkdir -p "$SCRATCH/$AQUIFER/$FRAME/mintpy"
    echo "  Pulling frame $FRAME..."
    a-get "$BUCKET/$AQUIFER/$FRAME/mintpy/" \
        -C "$SCRATCH/$AQUIFER/$FRAME/mintpy/"

    if [ ! -f "$SCRATCH/$AQUIFER/$FRAME/mintpy/timeseries.h5" ]; then
        echo "  ERROR: timeseries.h5 missing for frame $FRAME"
        exit 1
    fi
    echo "  ✓ Frame $FRAME ready"
done

echo "Disk usage after pulling: $(du -sh $SCRATCH | cut -f1)"

# ── Run decomposition ─────────────────────────────────────────
echo ""
echo "--- Running InSAR decomposition ---"
apptainer exec \
    --bind "$REPO:/repo" \
    --bind "$SCRATCH:/work" \
    "$SIF" \
    python /repo/src/transboundary_opera/run_decomposition.py \
        --aquifer-dir "/work/$AQUIFER"

# ── Check outputs ─────────────────────────────────────────────
echo ""
echo "--- Checking decomposition outputs ---"
# FIX: decomposer.py writes *_dhorz.h5 and *_dvert.h5 at the aquifer root
# Exclude anything inside mintpy/ subdirectories
DEFO_FILES=$(find "$SCRATCH/$AQUIFER" -maxdepth 1 -name "*.h5" ! -path "*/mintpy/*" | sort)
if [ -z "$DEFO_FILES" ]; then
    echo "WARNING: no decomposition .h5 files produced."
    echo "This may be normal if no ascending/descending overlap exists."
else
    echo "Decomposition outputs:"
    for f in $DEFO_FILES; do
        echo "  ✓ $(basename $f) ($(du -sh $f | cut -f1))"
    done
fi

# ── Upload decomposition outputs to Allas ────────────────────
if [ -n "$DEFO_FILES" ]; then
    echo ""
    echo "--- Uploading decomposition outputs to Allas ---"
    for f in $DEFO_FILES; do
        FNAME=$(basename "$f")
        a-put "$f" \
            -b "$BUCKET" \
            --object "$AQUIFER/$FNAME" \
            --nc
        echo "  Uploaded: $BUCKET/$AQUIFER/$FNAME"
    done
fi

# ── Cleanup ───────────────────────────────────────────────────
rm -rf "$SCRATCH"

echo ""
echo "============================================================"
echo "Decomposition for $AQUIFER complete: $(date -u)"
echo "============================================================"