#!/bin/bash
# ================================================================
# frame_job.sh — SLURM job: download + MintPy processing for one frame
# Generated by pipeline.py — do not edit manually
# ================================================================
#SBATCH --job-name=opera_{AQUIFER}_{FRAME_ID}
#SBATCH --account={CSC_PROJECT}
#SBATCH --partition={PARTITION}
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={CPUS}
#SBATCH --mem={MEM}
#SBATCH --time={TIME}
#SBATCH --gres=nvme:{NVME_GB}
#SBATCH --output={LOGS_DIR}/{AQUIFER}_{FRAME_ID}_%j.out
#SBATCH --error={LOGS_DIR}/{AQUIFER}_{FRAME_ID}_%j.err

# Exit immediately on any error
set -euo pipefail

# ── Job parameters (filled in by pipeline.py) ─────────────────
AQUIFER="{AQUIFER}"
FRAME_ID="{FRAME_ID}"
START_DATE="{START_DATE}"
END_DATE="{END_DATE}"
REF_LALO="{REF_LALO}"
OPERA_VERSION="{OPERA_VERSION}"
N_WORKERS="{N_WORKERS}"
CHUNK_SIZE="{CHUNK_SIZE}"
DL_WORKERS="{DL_WORKERS}"
REPO="{REPO}"
BUCKET="{BUCKET}"

echo "============================================================"
echo "Job: $SLURM_JOB_ID — Aquifer $AQUIFER — Frame $FRAME_ID"
echo "Date range: $START_DATE → $END_DATE"
echo "Node: $(hostname)"
echo "Started: $(date -u)"
echo "============================================================"

# ── Activate Allas ────────────────────────────────────────────
module load allas
allas-conf --silent

# ── Skip if already done ──────────────────────────────────────
if a-check "$BUCKET/$AQUIFER/$FRAME_ID/mintpy/velocity.h5" 2>/dev/null; then
    echo "Frame $FRAME_ID already has velocity.h5 in Allas — skipping."
    exit 0
fi

# ── Set up local NVMe scratch ─────────────────────────────────
SCRATCH="$LOCAL_SCRATCH/$SLURM_JOB_ID"
mkdir -p \
    "$SCRATCH/outputs" \
    "$SCRATCH/static_lyrs" \
    "$SCRATCH/geometry" \
    "$SCRATCH/mintpy"

echo "Scratch: $SCRATCH"
echo "Available disk: $(df -h $LOCAL_SCRATCH | tail -1)"

# ── Pull Apptainer container from Allas ──────────────────────
echo "Pulling container from Allas..."
a-get "$BUCKET/container/transboundary_opera.sif" -C "$SCRATCH/"
SIF="$SCRATCH/transboundary_opera.sif"
echo "Container ready: $(du -sh $SIF | cut -f1)"

# ── run1: download .nc files from AWS S3 ─────────────────────
echo ""
echo "--- run1: downloading DISP-S1 data ---"
apptainer exec \
    --bind "$REPO:/repo" \
    --bind "$SCRATCH:/work" \
    "$SIF" \
    python /repo/src/transboundary_opera/run1_download_DISP_S1_Static.py \
        --frameID    "$FRAME_ID" \
        --version    "$OPERA_VERSION" \
        --startDate  "$START_DATE" \
        --endDate    "$END_DATE" \
        --dispDir    /work/outputs \
        --staticDir  /work/static_lyrs \
        --geomDir    /work/geometry \
        --nWorkers   "$DL_WORKERS"

# Count downloaded files
NC_COUNT=$(find "$SCRATCH/outputs" -name "*.nc" | wc -l)
echo "Downloaded $NC_COUNT .nc files"
echo "Disk usage after download: $(du -sh $SCRATCH | cut -f1)"

# ── run2: process → H5 files ─────────────────────────────────
echo ""
echo "--- run2: processing with MintPy ---"
apptainer exec \
    --bind "$REPO:/repo" \
    --bind "$SCRATCH:/work" \
    "$SIF" \
    python /repo/src/transboundary_opera/run2_prep_mintpy_opera.py \
        -u "/work/outputs/*.nc" \
        -m /work/static_lyrs \
        -g /work/geometry \
        -o /work/mintpy \
        --water-mask-file esa_world_cover_2021 \
        --dem-file        glo_30 \
        --ref-lalo        "$REF_LALO" \
        --n-workers       "$N_WORKERS" \
        --chunk-size      "$CHUNK_SIZE"

# Verify outputs exist
echo ""
echo "--- Verifying outputs ---"
for f in timeseries.h5 velocity.h5 geometryGeo.h5 avgSpatialCoh.h5; do
    if [ -f "$SCRATCH/mintpy/$f" ]; then
        echo "  ✓ $f ($(du -sh $SCRATCH/mintpy/$f | cut -f1))"
    else
        echo "  ✗ $f MISSING — run2 may have failed"
        exit 1
    fi
done

# ── Upload H5 outputs to Allas ───────────────────────────────
echo ""
echo "--- Uploading outputs to Allas ---"
a-put "$SCRATCH/mintpy/" \
    -b "$BUCKET" \
    --object "$AQUIFER/$FRAME_ID/mintpy/" \
    --nc

echo "Uploaded to Allas: $BUCKET/$AQUIFER/$FRAME_ID/mintpy/"

# ── Delete raw .nc files (free scratch space) ────────────────
echo "Deleting raw .nc files..."
rm -rf "$SCRATCH/outputs"
echo "Disk usage after cleanup: $(du -sh $SCRATCH | cut -f1)"

# ── Final cleanup ─────────────────────────────────────────────
rm -rf "$SCRATCH"

echo ""
echo "============================================================"
echo "Frame $FRAME_ID complete: $(date -u)"
echo "============================================================"